### PR TITLE
set entity rendermode on color change

### PR DESCRIPTION
**Pull request by natrim**

### CODE REVIEW

**Comment by awilliamson** [comment]
Code does not follow guidelines stated in the readme, please amend.

**Comment by Xandaros** [comment]
Also, please make sure to keep the blank line at the end of the file. Looks good, though. Haven't even noticed changing alpha on entities not working.

**Comment by natrim** [comment]
the new line at end was not here in the file, it is now

**Comment by Xandaros** [comment]
Oh, my bad.

**Comment by awilliamson** [comment]
Why change the parameter name when we asked that you fix codestyle? It does not need to be changed. Clr -> Color was unnecessary and you also didn't change it in the LuaDoc comment above the function, therefore this would have broken documentation. Please don't rename the parameter if it wasn't called for.

**Comment by wraith321** [comment]
Also, why do you retrieve the color for the alpha check again, when you already have the color object?

**Comment by awilliamson** [comment]
Good spot @wraith321. Useless getColor call when you have the color object for what you just set.

**Comment by natrim** [comment]
btw. if holograms have entity methods, then we could probadly remove hologram_methods:setColor( color ) ?

as it seem's exactly same now

**Comment by Xandaros** [comment]
True. Do you want to make a PR for it?

**Pull request merged**
