### PR TITLE
Added wiring functions

### PR DESCRIPTION
**Pull request by davidsonbr**
Added functions for wiring and unwiring entities to each other, as well as getting inputs and outputs of entities. I figured that only wiring and unwiring should require permissions, being one could see inputs and outputs of any entity with the advanced wiring tool.

### CODE REVIEW

**Comment by Xandaros** [comment]
Looks pretty solid to me.
Just two minor things:
1. Please move this into the wire lib, we want to remove wire as a hard dependency
2. Please change the commit title, so it makes it only one change. Something like "add wiring capability". You can put the functions you added in the longer description :)
(I normally wouldn't mind the second one, but since you need to change it a little anyway, might as well fix that, too :) )

**Comment by davidsonbr** [comment]
The changes you requested should be working now. I changed the functions from being ent_metatable:func to wire_library.func as well as adding a parameter for the entity that would have been passed by doing so.

**Comment by awilliamson** [comment]
Would be nice for the wire functions to throw errors similar to how other libraries do it. Returning a bool & optional string isn't expected at all for that create function.

You've implemented SF throw for the permissions, any other checks which cause a fail state should throw with a relevant error message because the create function can't continue.

Also codestyle mistake on L308. Don't know if any others exist, please be careful and go through to ensure codestyle.

Can you make it so all the changes are in a single commit please?

Other than those, this looks really good and I look forward to accepting it.

**Comment by davidsonbr** [comment]
Just as a heads up, L90 - L273 contain styling errors, not relevant to my pull request. Might submit another once this one is merged.

**Comment by davidsonbr** [comment]
I changed the portions where the code should error to throw instead of return false, as well as searching for any styling errors in my portion of code.

There is now only one commit to be pulled, looking forward to this being in the development branch.

**Comment by Xandaros** [comment]
Merged manually, see: bf55ca5acbba892da791343d656d21bdb066e209
Did some minor code-style changes for you.

**Pull request closed without merging**
