### PR TITLE
Added file.createDir function

### PR DESCRIPTION
**Pull request by davidsonbr**

### CODE REVIEW

**Comment by Xandaros** [comment]
Looks good to me

**Comment by Jazzelhawk** [comment]
I know it's a bit late now but shouldn't `error( "path contains '..'" )` be something like `SF.throw( "path contains '..'", 2 )` except a little more detailed? 

And also the `@return` message says it returns an error message but, I don't think garry's CreateDir returns anything.

**Comment by Xandaros** [comment]
Yeah, it should be SF.throw...

And the CreateDir function does seem to be completely silent. It just fails to do anything if you give it an invalid path...

**Comment by awilliamson** [comment]
Thanks for the spot @Jazzelhawk, clearly @Xandaros and I are not on point today.

If createDir is silent on GMod side then the return isn't necessary; however, if it changes in the future the return would still work.

Seeing as how the `@return` should reflect as close to createDir as possible, it should be altered to have no return, and the function call should be separate from the return statement of the function. Would like to know @Xandaros thoughts on this.

**Pull request merged**
