### PR TITLE
Added includedir preprocessor

### PR DESCRIPTION
**Pull request by davidsonbr**
User specifies a directory and all files in the directory are included. Does not recursively include directories.

### CODE REVIEW

**Comment by awilliamson** [comment]
A few lines with incorrect codestyle. Some odd things going on with indentation for tabs/spaces.

Will need to test this out, can't see it being a problem. Definitely nice functionality, I know people building their own extensive libs will love this.

**Comment by davidsonbr** [comment]
Felt like going on a code style spree today, so I fixed the errors with code style as well as the commits themselves.

**Comment by Jazzelhawk** [comment]
I've had a look at this and there's a few things that need pointing out.

On [line 320](https://github.com/INPStarfall/Starfall/pull/291/files#diff-4da1c93b97f4073225684daa2f2e099bR320) the for loop needs to start at 1 otherwise the function does not work.

[This line](https://github.com/INPStarfall/Starfall/pull/291/files#diff-0e99545f3cfad91a963c8d00b7a9c862R178) could be a little clearer since all preprocessor statements are optional.

The loadpriority feature makes it so that files are executes twice which may not be desirable. This could be easily fixed by storing the result from the scripts in the returns table when the scripts are executed in the loadpriority part and then checking if it's already been executed like you did on [line 290](https://github.com/INPStarfall/Starfall/pull/291/files#diff-4da1c93b97f4073225684daa2f2e099bR290)

Other than those things, it looks good. Once they are resolved, @awilliamson can manually merge this PR.

**Comment by davidsonbr** [comment]
Fixed everything that you listed. Good to go.

**Comment by awilliamson** [comment]
@Jazzelhawk EpicG rebased the changes and fixed those conflicts. Just give this a once over to make sure what you recommended has been implemented, then feel free to accept.

**Comment by Jazzelhawk** [comment]
Scripts are still being executed twice. With requiredir it _appears_ like they are being executed once each only because the require function checks if the file has already been required. 
Just add `returns[ file ] =` on lines 285 and 326.

Sorry for being pedantic but "This will include **all** files in the directory" is not strictly true, it should probably mention that directories are not recursively included.

**Comment by Xandaros** [comment]
Might be a good idea to add a parameter for recursive including, actually.

**Comment by davidsonbr** [comment]
Would it be with another preprocessor?
Maybe "includeall"?

**Comment by Xandaros** [comment]
That could work, but another possibility just came to my mind: Allow wildcards.
I have not really thought of this, so don't give it too much value, but what if we allowed something like `--@include libs/gameenginge/vectors/*` and `--@include libs/gameengine/**`, where the first includes everything in that directory only and the second includes it recursively.

This might be a bit unintuitive for new users, but I'd argue that it is more readable than throwing dozens of preprocessor statements at them.
(Of course, this would shadow names with asterisks in them[or files that are only names "_" and "_*", depending on the implementation], making them inaccessible... I am willing to make that sacrifice)

**Comment by davidsonbr** [comment]
I can hop on board with that, but would this PR be necessary then? Would we just make a new PR?

**Comment by Xandaros** [comment]
It would make all of this superfluous... sorry :(

**Comment by awilliamson** [comment]
Use of asterisk should be preferred, as this mimics terminal use-case, and makes the `--@include` directive a bit more robust.

A simple example use-case can be constructed and thrown in the examples for users, I'd argue `*` is a fairly intuitive concept in computing.

@EpicG The code you have for sub-dirs would still be valid, it just needs to be renamed and rebundled under the `--@include` preproc, filtering for `*` and `**` as 'switches'.

**Comment by davidsonbr** [comment]
#346

**Pull request closed without merging**
