### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by davidsonbr**
Issue #7 

If need be, I can squash all of these into one commit.

### CODE REVIEW

**Comment by Jazzelhawk** [comment]
Nice, did you use a script to do this or did you do it all manually?
Also the only problem I see with this is that it may make current pull requests unable to automatically merge.

**Comment by davidsonbr** [comment]
I was tempted to write a script for this, but it was all manual.

**Comment by awilliamson** [comment]
I've just gone through files changed. Yes, it took a while. Obviously there were a few instances where the codestyle was missed, or blocks of repeated code weren't consistent ( Changing 1 liners to blocks, but not changing them all to blocks ).

As far as I can tell there should be 0 impact on performance. I haven't tested all of SF functionality with these changes, but from inspection none of them modify behaviour, just cosmetics.

Hopefully this won't break any current PR's. :)

**Comment by awilliamson** [comment]
It did break current PRs :(

**Pull request merged**
