### PR TITLE
Editor improvements

### PR DESCRIPTION
**Pull request by Jazzelhawk**
Made completions list load libraries and types more dynamically apart from a few exceptions
Completions made nicer and added showing completions for types after typing a colon
Function names, parameters and preprocessor statements have better highlighting
Fixed a spelling mistake for an option and adjusted scroll speeds for the editor and the completion popup

#361

### CODE REVIEW

**Comment by davidsonbr** [comment]
Would it be better to modify the angles, vectors, and color libraries so that the checks at [L49](https://github.com/Jazzelhawk/Starfall/blob/b061682646d4b03e6bfbb7e68003b145f5f7bfe1/lua/starfall/editor.lua#L49) don't have to be present?

**Comment by Jazzelhawk** [comment]
Maybe, I'll have a look. I have an idea but if there needs to be another table on the library's table then there's still going to be exceptions

**Comment by davidsonbr** [comment]
It does seem kind of redundant ( and bad ) to have library related variables in the SF table itself ( SF.Entities, SF.Angle, etc. ) instead of something like SF.Libraries.libraries.Entities.

**Comment by Jazzelhawk** [comment]
The only thing I can think of would be to alter the SF.Typedef function [here](https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/sflib.lua#L115) by adding another line saying something like `metamethods.methods = methods` so that there will always be something that references to the methods table for all types.

**Comment by davidsonbr** [comment]
The metatables already have their (un)wrappers under `metatable.__wrap` and `metatable.__unwrap`, so I think the methods should be stored in `metatable.__methods` to maintain the pattern.

That would also eliminate the need for `SF.Entities` and other respective tables because they could be retrieved with `SF.GetTypeDef`.

Only problem is some libraries store their library functions in the SF.$lib table. Again it can retrieved with `SF.Libraries.Get`.

With the scope of this PR I suggest that you only add `metamethods.__methods` to resolve the __index overrides.

**Comment by Jazzelhawk** [comment]
Okay, added the `metamethods.__methods` and edited the types in which `__index` is overwritten

**Pull request merged**
