### PR TITLE
Fix of spelling mistakes in Readme #377

### PR DESCRIPTION
**Pull request by suunr**

### CODE REVIEW

**Comment by awilliamson** [comment]
Could you make it multiline for tbl2? I believe that was the original intention, if you consider the original styling in markdown.

**Comment by suunr** [comment]
I couldn't do it multiline without adding an empty line at the end.

**Comment by davidsonbr** [comment]
```
local tbl2 = {
    "Multi-line",
    2,
    lastVal
} 
```

What do you mean? This works fine without an empty line at the end.

**Comment by suunr** [comment]
- Point 1
- Point 2 `
  local tbl2 = {
  "Multi-line",
  2,
  lastVal
  } 
  `

```
local tbl2 = {
    "Multi-line",
    2,
    lastVal
} 
```

You can't make code with more than one line in a list. It will automatically convert it into one line code.

**Comment by davidsonbr** [comment]
Oh I see what you are saying now.

~~I thought you were talking about the empty line on L49, which should not be there.~~
I'm dumb.

**Comment by suunr** [comment]
If you remove the empty line on L49 the code will get formatted in one line.

**Pull request merged**
