### PR TITLE
New Starfall Editor

### PR DESCRIPTION
**Pull request by Jazzelhawk**
Complete overhaul of the Starfall Editor, using the Ace code editor.

If you ever update the Ace editor files, remember to put the license in the ace.js file.

### CODE REVIEW

**Comment by davidsonbr** [comment]
Looks nice, although I have no say in the merge of your PR.
image

I really like the lock / undock of the file viewer, but the only thing I don't like is the default layout, how the file viewer is slightly overlapping the editor. 
image

**Comment by Jazzelhawk** [comment]
Hmm, never noticed that, I'll try and see if I can fix that

Edit: Amended the commit, should be fine now

**Comment by awilliamson** [comment]
@Jazzelhawk Initial commit... and no auto merge :c 

@EpicG Played around with it last week, He's been holding off on the PR :P It's very nice, we'll be doing a few tweaks once it's through though.

**Comment by Jazzelhawk** [comment]
Changed the commit message and fixed conflict issues

**Comment by davidsonbr** [comment]
When opening the editor in multiplayer I get the following into my console:

```
[HTML] Uncaught ReferenceError: ace is not defined
[HTML] Uncaught ReferenceError: ace is not defined
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Object #<HTMLDivElement> has no method 'setOption'
[HTML] Uncaught TypeError: Cannot call method 'addCommand' of undefined
[HTML] Uncaught ReferenceError: ace is not defined
[HTML] Uncaught TypeError: Cannot read property '0' of undefined
```

image

**Comment by Jazzelhawk** [comment]
That error should be fixed now, I made it so the editor files are sent to the client upon connecting to a server over net.

**Comment by davidsonbr** [comment]
Nice, another thing that I noticed is that when pressing "~" ( Shift + ' ) my console opens even though it is bound to "`". Same with "@" ( Shift + 2 ).

**Comment by Jazzelhawk** [comment]
Try going on settings and then turn on/off the console fix, maybe I should have that disabled by default

**Comment by awilliamson** [comment]
'Console bug' setting is disabled by default for me. When I press ' ` ' which is my console bind, console opens for a fraction of a second before closing.

I'm debating whether to just leave out the 'console opens on bind press' "fix", as it will be a hack to get working.

As we're both UK based, I'd like some input from our non-UK friends on how this performs on their setup with their keyboards.

I noticed that Save & Exit is missing the '&' symbol as well. Other than those it's ready for a merge, and to be released into the big bad world.

**Comment by awilliamson** [comment]
I'd prefer this to be in several logical commits, rather than a huge chunk. As you've been adding features steadily, so it would be nice to keep that history for future debugging. Such a big merge will be a pain to debug without a rich history.

**Comment by thegrb93** [comment]
Can you make middle clicking a tab close the tab?

Also, can you make ctrl+q close the editor?

One last thing, clicking save or doing ctrl+s should default to save-as if the file hasn't been saved before.

**Comment by thegrb93** [comment]
Whenever you click and hold to select text, if you release the mouse while outside of the text area, the selecting functionality won't stop until clicking and releasing again while inside the text area.

**Comment by Jazzelhawk** [comment]
@thegrb93 I don't feel that the first two changes you suggest are necessary, so maybe once the PR is accepted you can add them in and let the owners decide whether they think they should be added.

About the selection thing, I noticed that ages ago. Unfortunately there isn't anything I can do to fix it, because it is to do with the way GMod handles html panels.

**Comment by thegrb93** [comment]
I feel they are necessary because the old editor has them and I used them a lot. Is there no hack that can be used to fix the html select issue?

**Comment by thegrb93** [comment]
Here's code for middle click. Just put in line 560 in sfderma.lua

```
function tab:DoMiddleClick()
    SF.Editor.removeTab(self)
end
```

**Comment by thegrb93** [comment]
Is it possible to have the html frame accept input upon opening a file or opening the editor? Currently you have to actually click in the text area to start entering code.

**Comment by thegrb93** [comment]
Here's the ctrl+q code. Add this to line 73 of editor.html

```
editor.commands.addCommand({
                name: "quit",
                bindKey: {win: "Ctrl-Q", mac: "Command-Q"},
                exec: function(editor){
                    console.log("RUNLUA:SF.Editor.close()");
                }
            });
```

**Comment by Jazzelhawk** [comment]
I added the quit keybind but only because the last commit involves moving the save keybind.

The reason you have to click the main window is because when you click in a file, the file viewer has focus and so the main window doesn't accept keyboard input. I tried to get it to focus the main window but I couldn't get it to work.

**Comment by thegrb93** [comment]
Hm, yeah. I see the file viewer has focus after opening the editor which probably isn't too hard to fix, but after clicking the code editor and giving the code editor focus, it still won't accept input unless you click inside the text area. This seems to only happen after closing the opening the editor though. If you leave focus and re-enter focus of the editor without closing it, it will allow text input without having to click in the text field.

**Comment by thegrb93** [comment]
I think the javascript editor is relying on mouse input to know whenever it has focus or not.

**Comment by thegrb93** [comment]
Here you go. Fixes the file browser taking focus and the editor not getting focus after opening the editor frame.

In editor.lua after editor:AddComponent( "htmlPanel", html )

```
function editor:OnOpen()
            html:Call("editor.focus()")
            html:RequestFocus()
        end
```

In sfderma.lua line 363

```
function PANEL:open()
    for k, v in pairs( self.lockChildren ) do
        if v.locked then
            v:open()
        end
    end

    self:SetVisible( true )
    self:SetKeyBoardInputEnabled( true )
    self:MakePopup()
    self:InvalidateLayout( true )

    if self.OnOpen then
        self:OnOpen()
    end
end
```

**Comment by thegrb93** [comment]
Note: I changed the open function so the lockChildren get opened first.

**Comment by Jazzelhawk** [comment]
I added the middle mouse click and the focus fix. That was pretty helpful xD

**Comment by thegrb93** [comment]
Alright cool I think it's ready

**Pull request merged**
