### PR TITLE
Fixed helper showing html tags

### PR DESCRIPTION
**Pull request by Jazzelhawk**

### CODE REVIEW

**Comment by davidsonbr** [comment]
Wouldn't `</br>` be replaced with `\n`?

**Comment by Jazzelhawk** [comment]
It would seem like so but it ends up looking correct on the helper because LuaDoc puts in `\n` after each line of comments from the source code.

**Comment by awilliamson** [comment]
@EpicG @Jazzelhawk Is this good to go?

**Comment by davidsonbr** [comment]
Looks good to me, unless @Jazzelhawk wants to change anything.

**Comment by Jazzelhawk** [comment]
Good to go.

**Pull request merged**
