### PR TITLE
Added model pre-processor statement

### PR DESCRIPTION
**Pull request by Jazzelhawk**
Issue: #249

### CODE REVIEW

**Comment by Jazzelhawk** [comment]
Fixed this PR, works much better now and I also added a 'hologram' for the processor and screen tools to preview their placement.

**Comment by awilliamson** [comment]
Do we still have those "Physics" issues with models? I think we still have 'paste' issues with the editor, which results in client-hangs. The most common use-case of --@model would be to copy from clipboard from the Q menu and paste.

It takes a good few minutes for the client to unlock, and even then nothing is pasted in the editor. I know we've had this issue before, but it really does need addressing. I don't feel that adding this feature in would be beneficial if it crashes/hangs 99% of the time it's intended to be used.

I presume this bug is present on the windows build of GMod as well? Can you confirm this?

EDIT: Other than that, the holograms are nice, bit 'jittery'. I'll delve further into the code soon(tm) and report back.

**Comment by awilliamson** [comment]
When spawning a proc with a oildrum model, had lua error:

``` lua
[ERROR] addons/starfall/lua/weapons/gmod_tool/stools/starfall_processor.lua:146: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. v - addons/starfall/lua/weapons/gmod_tool/stools/starfall_processor.lua:146
    3. unknown - lua/includes/modules/hook.lua:84
```

This is because the entity isn't yet fully initialised when the toolgun hovers over it. Make sure the entity is valid before calling any ent methods on the trace entity. This will also happen for screen as well.

I also see that 'updating' an existing chip doesn't change the model, I'm guessing this is to prevent the previously mentioned physics issues.

**Comment by Jazzelhawk** [comment]
Updating the model is pretty much impossible because constraints wouldn't be updated with the new model and the collision box doesn't update properly. I think that only setting the model when it first spawns is acceptable. It is also what E2 does.

Unfortunately the pasting issue is only on linux and there's nothing I can do to fix it. I posted this [issue](https://github.com/Facepunch/garrysmod-issues/issues/1958) on the garrysmod issues page a while ago but nothing seems to be done about it.

I don't know what causes the jitteriness but E2 seems to have a jitter aswell.

**Comment by Xandaros** [comment]
Updating the model won't work and it would be pretty awkward, I think.

I didn't know the past issues were only on Linux. I was blaming the E2 editor all along :D (That needs to be fixed, though... very irritating)

**Pull request merged**
